### ISSUE TITLE
Server Running Error?

### ISSUE THREAD

**Issue by LLTae2** [GangSeoGoo/GangSeoDragon-Backend#1]
I cloned donggyeom's repo. After that I runned the server. But errors occured. Like this picture.
![image](https://user-images.githubusercontent.com/80657114/176887447-6e661afd-41c5-4eda-8378-5099e6bec585.png)

**Comment by zakk616** [comment]
did you install the dependencies it requires?
**inside repo folder run:**
`npm install`
`cd server`
`node server.js`

**Comment by zakk616** [comment]
error says you do not have `mysql ` installed on your system.
kindly go through this [link ](https://www.npmjs.com/package/mysql)and folow to install and configure `mysql `first

**Comment by LLTae2** [comment]
I solved the error. THX
