### ISSUE TITLE
recommend table rvavg

### ISSUE THREAD

**Issue by jsm8109jsm** [GangSeoGoo/GangSeoDragon-Backend#4]
![image](https://user-images.githubusercontent.com/105054567/177670245-fe9af951-b4b0-4a7c-9c1b-6b195d281053.png)

소수 첫째 자리에서 반올림되게 해주세요

**Comment by jeongdonggyeom** [comment]
네 알겠습니다

**Comment by jsm8109jsm** [comment]
아니면 정수 단위에서 반올림되게 하는게 더 편할 것 같네요

**Comment by jeongdonggyeom** [comment]
select t.tourNum, t.tourName, round(avg(r.reviewStar), 1) as rvavg, t.tourImage, t.tourExplain from review r, tourlist t where t.tourNum = r.tourNum and t.outside = ${data} group by tourNum, outside, tourName, tourImage, tourExplain order by rvavg DESC, t.tourNum

router.js 66번줄 문자열에 붙여 넣어주세요
